name: Node CI

on:
  push:
    branches: [main]

jobs:
  integrar-ci:
    runs-on: ubuntu-latest

    steps:
      - name: crear carpeta
        run: mkdir carpeta

      - name: Mostrar directorios
        run: ls

      - name: Mostrar fecha
        run: date
