name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: prefijo-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integrar-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Mostrar version de node
        run: node -v

      - name: Instalar dependencias
        run: pnpm install

      - name: Verificar formato
        run: pnpm lint

      - name: Correr tests
        run: pnpm test

      - name: Build
        run: pnpm build
